stages:
    - prepare
    - generate
    - deploy

gen-wraps:
    stage: prepare
    image: python:latest
    script: ./gen.py wraps wraps_gen
    artifacts:
        paths:
            - wraps_gen

gen-site:
    stage: generate
    image: robinmarchart/meson-builder:site-builder
    script: 
        - cd wraps-site
        - yarn install --frozen-lockfile --check-files --non-interactive
        - node node_modules/.bin/gatsby build --prefix-paths meson-wraps
    artifacts:
        paths:
            - wraps-site/public
    dependencies:
        - gen-wraps
    cache:
        policy: pull-push
        key: node_modules
        paths:
            - wraps-site/node-modules

pages:
    stage: deploy
    dependencies:
        - gen-site
    artifacts:
        paths:
            - public
    script: cp -r wraps-site/public ./
    rules:
        - if: $CI_COMMIT_BRANCH == "master"
    

